[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world = "6uN7xTWQHT31nLaeoREvmcL79bqd6KAzVvmGpn3pRCYv"

[programs.testnet]
hello_anchor = "6uN7xTWQHT31nLaeoREvmcL79bqd6KAzVvmGpn3pRCYv"

[programs.devnet]
hello_anchor = "6uN7xTWQHT31nLaeoREvmcL79bqd6KAzVvmGpn3pRCYv"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/aleynaalangil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "cargo run"
